# Generated by Django 4.2.17 on 2024-12-23 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLocationType',
            fields=[
                ('companytypeid', models.AutoField(db_column='companyTypeID', primary_key=True, serialize=False)),
                ('companytype', models.CharField(db_column='companyType', max_length=255)),
            ],
            options={
                'db_table': 'companytype',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('emailid', models.AutoField(db_column='emailID', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
            ],
            options={
                'db_table': 'email',
            },
        ),
        migrations.CreateModel(
            name='NumberType',
            fields=[
                ('numbertypeid', models.AutoField(db_column='numberTypeID', primary_key=True, serialize=False)),
                ('numbertype', models.CharField(db_column='numberType', max_length=255)),
            ],
            options={
                'db_table': 'numbertype',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('regionid', models.AutoField(db_column='regionID', primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={},
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personid', models.AutoField(db_column='personID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstName', max_length=255)),
                ('lastname', models.CharField(db_column='lastName', max_length=255)),
                ('address', models.ForeignKey(blank=True, db_column='address', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('numberid', models.AutoField(db_column='numberID', primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=255)),
                ('numbertype', models.ForeignKey(db_column='numberType', on_delete=django.db.models.deletion.DO_NOTHING, to='core.numbertype')),
            ],
            options={
                'db_table': 'number',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyid', models.AutoField(db_column='companyID', primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('defaultnumber_fax', models.ForeignKey(blank=True, db_column='defaultNumber_fax', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_fax', to='core.number')),
                ('defaultnumber_phone', models.ForeignKey(blank=True, db_column='defaultNumber_phone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_phone', to='core.number')),
                ('defaultperson', models.ForeignKey(blank=True, db_column='defaultPerson', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='PersonNumberLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.ForeignKey(db_column='number', on_delete=django.db.models.deletion.CASCADE, to='core.number')),
                ('person', models.ForeignKey(db_column='person', on_delete=django.db.models.deletion.CASCADE, to='core.person')),
            ],
            options={
                'db_table': 'personnumberlink',
                'unique_together': {('person', 'number')},
            },
        ),
        migrations.CreateModel(
            name='PersonEmailLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to='core.email')),
                ('person', models.ForeignKey(db_column='person', on_delete=django.db.models.deletion.CASCADE, to='core.person')),
            ],
            options={
                'db_table': 'personemaillink',
                'unique_together': {('person', 'email')},
            },
        ),
        migrations.CreateModel(
            name='CompanyLocationLink',
            fields=[
                ('companylocationlinkid', models.AutoField(db_column='companyLocationLinkID', primary_key=True, serialize=False)),
                ('company', models.ForeignKey(db_column='company', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('location', models.ForeignKey(db_column='location', on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
            options={
                'db_table': 'companylocationlink',
                'unique_together': {('company', 'location')},
            },
        ),
        migrations.CreateModel(
            name='CompanyEmailLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(db_column='company', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to='core.email')),
            ],
            options={
                'db_table': 'companyemaillink',
                'unique_together': {('company', 'email')},
            },
        ),
    ]
