# Generated by Django 4.2.17 on 2024-12-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemid', models.AutoField(db_column='itemID', primary_key=True, serialize=False)),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('lastprice', models.CharField(blank=True, db_column='lastPrice', max_length=255, null=True)),
                ('lastsupplier', models.CharField(blank=True, db_column='lastSupplier', max_length=255, null=True)),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iteminventory',
            fields=[
                ('iteminventoryid', models.AutoField(db_column='itemInventoryID', primary_key=True, serialize=False)),
                ('stock', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'iteminventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itemtype',
            fields=[
                ('itemtypeid', models.AutoField(db_column='itemTypeID', primary_key=True, serialize=False)),
                ('itemtype', models.CharField(db_column='itemType', max_length=255)),
            ],
            options={
                'db_table': 'itemtype',
                'managed': False,
            },
        ),
    ]
