# Generated by Django 4.2.17 on 2024-12-23 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_companylocationtype_email_numbertype_region_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('materialid', models.AutoField(db_column='materialID', primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='MaterialInventory',
            fields=[
                ('materialinventoryid', models.AutoField(db_column='materialInventoryID', primary_key=True, serialize=False)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('companylocationlink', models.ForeignKey(db_column='companyLocationLink', on_delete=django.db.models.deletion.CASCADE, to='core.companylocationlink')),
                ('material', models.ForeignKey(db_column='material', on_delete=django.db.models.deletion.CASCADE, to='inventory.material')),
            ],
            options={
                'db_table': 'materialinventory',
                'unique_together': {('material', 'companylocationlink')},
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('materialtypeid', models.AutoField(db_column='materialTypeID', primary_key=True, serialize=False)),
                ('materialtype', models.CharField(db_column='materialType', max_length=255)),
            ],
            options={
                'db_table': 'materialtype',
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('measureid', models.AutoField(db_column='measureID', primary_key=True, serialize=False)),
                ('measure', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'measure',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.AutoField(db_column='productID', primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('productinventoryid', models.AutoField(db_column='productInventoryID', primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('companylocationlink', models.ForeignKey(db_column='companyLocationLink', on_delete=django.db.models.deletion.CASCADE, to='core.companylocationlink')),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'db_table': 'productinventory',
                'unique_together': {('product', 'companylocationlink')},
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('producttypeid', models.AutoField(db_column='productTypeID', primary_key=True, serialize=False)),
                ('producttype', models.CharField(db_column='productType', max_length=255)),
            ],
            options={
                'db_table': 'producttype',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('transactiontypeid', models.AutoField(db_column='transactionTypeID', primary_key=True, serialize=False)),
                ('transactiontype', models.CharField(db_column='transactionType', max_length=255)),
            ],
            options={
                'db_table': 'transactiontype',
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterModelOptions(
            name='iteminventory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemtype',
            options={},
        ),
        migrations.CreateModel(
            name='ProductTransaction',
            fields=[
                ('producttransactionid', models.AutoField(db_column='productTransactionID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('transactiondate', models.DateTimeField(auto_now_add=True, db_column='transactionDate')),
                ('companylocationlink', models.ForeignKey(db_column='companyLocationLink', on_delete=django.db.models.deletion.CASCADE, to='core.companylocationlink')),
                ('productinventory', models.ForeignKey(db_column='productInventory', on_delete=django.db.models.deletion.CASCADE, to='inventory.productinventory')),
                ('transactiontype', models.ForeignKey(db_column='transactionType', on_delete=django.db.models.deletion.CASCADE, to='inventory.transactiontype')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'producttransaction',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='producttype',
            field=models.ForeignKey(db_column='productType', on_delete=django.db.models.deletion.CASCADE, to='inventory.producttype'),
        ),
        migrations.CreateModel(
            name='MaterialTransaction',
            fields=[
                ('materialtransactionid', models.AutoField(db_column='materialTransactionID', primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transactiondate', models.DateTimeField(auto_now_add=True, db_column='transactionDate')),
                ('companylocationlink', models.ForeignKey(db_column='companyLocationLink', on_delete=django.db.models.deletion.CASCADE, to='core.companylocationlink')),
                ('materialinventory', models.ForeignKey(db_column='materialInventory', on_delete=django.db.models.deletion.CASCADE, to='inventory.materialinventory')),
                ('transactiontype', models.ForeignKey(db_column='transactionType', on_delete=django.db.models.deletion.CASCADE, to='inventory.transactiontype')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'materialtransaction',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='materialtype',
            field=models.ForeignKey(db_column='materialType', on_delete=django.db.models.deletion.CASCADE, to='inventory.materialtype'),
        ),
        migrations.AddField(
            model_name='material',
            name='measure',
            field=models.ForeignKey(db_column='measure', on_delete=django.db.models.deletion.CASCADE, to='inventory.measure'),
        ),
        migrations.CreateModel(
            name='ProductConsumerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companylocationlink', models.ForeignKey(db_column='companyLocationLink', on_delete=django.db.models.deletion.CASCADE, to='core.companylocationlink')),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'db_table': 'productconsumerlink',
                'unique_together': {('product', 'companylocationlink')},
            },
        ),
        migrations.CreateModel(
            name='MaterialManufacturerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(db_column='company', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('material', models.ForeignKey(db_column='material', on_delete=django.db.models.deletion.CASCADE, to='inventory.material')),
            ],
            options={
                'db_table': 'materialmanufacturerlink',
                'unique_together': {('material', 'company')},
            },
        ),
    ]
